### ISSUE TITLE
`docker-compose.yml` がフォークリポジトリとしては不適切な形で存在している

### ISSUE THREAD

**Issue by yuicho** [kmycode/mastodon#484]
# 問題点
現状、Docker Compose における設定を記述する `docker-compose.yml` で、本家Mastodonとは違うソフトウェアにも関わらず、イメージ名が `ghcr.io/mastodon/mastodon` になっています。
https://github.com/kmycode/mastodon/blob/46161e53484cab9c9c7a3e19501cf937d3c72f0e/docker-compose.yml#L59
`ghcr.io/mastodon/mastodon` は、UpstreamでビルドされるバニラMastodonのイメージです。

なお、`build` 行も存在しているため即時問題につながる可能性は低いと思われますが、不適切な状態です。

# 背景
Upstream（本家）のMastodonでは、github acction によって自動でイメージがbuildされ GitHub Container Registry（ghcr.io）へ自動的にpushされます。
そのため、image名が `ghcr.io/mastodon/mastodon` に設定されています。
（なお、build行も存在しているために実際にはイメージ名でこれが用いられるのみで、リポジトリ内のファイル群を用いてbuildされるようです）

**Comment by yuicho** [comment]
他の問題と合わせてfixしようと思ったのですが、composeファイルにてリファクタリングを行うPRが出されている（mastodon/mastodon#28148）ため、このリファクタリングを待ってからfixしたいと思っています

**Comment by yuicho** [comment]
もうすぐ4.3リリースなのになかなかマージされないなと思っていたら、最低限の修正だけに絞ったPRが別でオープンされていました…
そして、すでにマージされていました……

mastodon/mastodon#31554

**Comment by yuicho** [comment]
さらにその後、`build`句を使わず、すでにbuildされたimageを指定する形に変更されました。
mastodon/mastodon#31615

```yaml
  web:
    # You can uncomment the following line if you want to not use the prebuilt image, for example if you have local code changes
    # build: .
    image: ghcr.io/mastodon/mastodon:v4.3.0-beta.1
```
https://github.com/mastodon/mastodon/blob/04f0468016b450ace8e0ce707b4c21aa18b51262/docker-compose.yml#L59-L62

```yaml
  streaming:
    # You can uncomment the following lines if you want to not use the prebuilt image, for example if you have local code changes
    # build:
    #   dockerfile: ./streaming/Dockerfile
    #   context: .
    image: ghcr.io/mastodon/mastodon-streaming:v4.3.0-beta.1
```
https://github.com/mastodon/mastodon/blob/04f0468016b450ace8e0ce707b4c21aa18b51262/docker-compose.yml#L81-L86

（しかもなぜかsidekiqだけはそのままになってます…）
```yaml
  sidekiq:
    build: .
    image: ghcr.io/mastodon/mastodon:v4.3.0-beta.1
```
https://github.com/mastodon/mastodon/blob/04f0468016b450ace8e0ce707b4c21aa18b51262/docker-compose.yml#L102-L104

これにより、当issue作成時に記載した

> （なお、build行も存在しているために実際にはイメージ名でこれが用いられるのみで、リポジトリ内のファイル群を用いてbuildされるようです）

は崩れ、本家Mastodonのイメージを使用する形に書き変わってしまいました。

**Comment by yuicho** [comment]
現状kmyblueを`git clone`して`docker compose up -d`とかすると、本家Mastodonが動作することとなります。

フォークとして取り得る動きとしては下記4点が考えられるかと思います。
1. Upstreamに元の形式に戻すように要望（PR）
2. kmyblue内だけで正常な形へfix
3. このまま放置しUpstreamに合わせる
4. `docker-compose.yaml`を消してしまう

1に関しては、本家には全く問題のない事項なので、少々躊躇われるものがあります。

したがってkmyblueリポジトリ内でなんとかするならば2ということになります。
しかしながら、今後該当部分が本家と違う状態で維持し続けることとなりますので、本家のコミットを取り込むときに少々面倒かもしれません。
`docker-compose.yaml`が書き換わるのは稀有な気もしますが、初めのリファクタリングPRがまだ動いてるので、今後も変更はかかると思います。

そもそもkmyblueはDockerでの動作をサポートしていないので、3の放置でも構わないとは思います。
…が、`docker-compose.yaml`が存在することでDockerComposeで動作できると勘違いしてしまう可能性も考えられます。
（そして立ち上がるのは本家Mastodonなので余計にややこしいです）

というわけで、4のファイルそのものを消してしまうというのも一つの手なのかなと考えています。
いずれにせよこのままでは`docker-compose.yaml`ファイルは使えず自分で書く必要が出てくるため、消しても大した問題にはならないと思います（参考にしようと思ったときに本家に見に行かないといけないぐらい？）。

これは今後メンテする上での負荷等にも関わってくる話ではありますので、 @kmycode さんのご意見をお聞きしたく思っております…🙏

**Comment by kmycode** [comment]
前提としてkmyblueのメインのメンテナはDockerの知識が全く無く、kmyblueの開発以外にもやることが大量にあるのでDockerに構っていられないというのがあります。
そのうえで、QiitaなどあちこちのブログでDockerを使ってさくっと立ち上げるという記事をよく見ますけど、Dockerは簡単に環境を構築するものだと思ってまして、それと同じ感覚でうちを使われるとご指摘の件もあってデメリットが上回ると考えます。

１は完全にうちだけの都合なので出しづらく、２も、あすかにPRを承認・レビューする能力がないので、小規模プロジェクトである今はやらないほうが安全だと思います
３も考えましたが、今は４がいいと思います。

本家の4.3.0が正式リリースされるまで待ちますが、もしダメでしたら次回LTSでは`docker-compose.yml`を削除する方向でいきましょう。

**Comment by kmycode** [comment]
@yuicho すみません、ああ言った手前で申し訳ないのですけども、`docker-compose.yml`ちゃんと見てみたらフォークでも簡単に修正できるよう配慮していると思われる記述がありました

```yml
  web:
    # You can uncomment the following line if you want to not use the prebuilt image, for example if you have local code changes
    # build: .
    image: ghcr.io/mastodon/mastodon:v4.3.0-rc.1
```

なのでこれを以下のように修正すればいいんじゃないかと思うのですが、いかがでしょうか？`image`をコメントアウトする必要はありますか？

```yml
  web:
    # You can uncomment the following line if you want to not use the prebuilt image, for example if you have local code changes
    build: .
    # image: ghcr.io/mastodon/mastodon:v4.3.0-rc.1
```

```yml
  streaming:
    # You can uncomment the following lines if you want to not use the prebuilt image, for example if you have local code changes
    build:
      dockerfile: ./streaming/Dockerfile
      context: .
    # image: ghcr.io/mastodon/mastodon-streaming:v4.3.0-rc.1
```

なお`sidekiq`は最初からこうなってましたが、`image`をコメントアウトしたほうがいいですか？

```yml
  sidekiq:
    build: .
    image: ghcr.io/mastodon/mastodon:v4.3.0-rc.1
```

この修正に対応したPRを作っておきます。なにかコメントがあれば、PRのコード内に直接コメントするなり、このIssueに追記するなりお願いします

**Comment by yuicho** [comment]
経緯が一箇所に纏まってる方が後々のためにいいかなーと思いますので、まずこちらにコメントさせていただきますね

記述についてですが、`web`と`streaming`はそれでも問題はないかと思います。
メンテ上差し支えないのであれば、以下のようにkmyblueとして独自のimage名を指定してやるのが適切ではあります。
…が、kbのバージョンが変わるたびに修正する必要が生まれてしまうので、この点はメンテコストと相談ください。

```yaml
  web:
    # You can uncomment the following line if you want to not use the prebuilt image, for example if you have local code changes
    build: .
    image: kmyblue:15.0
```

```yaml
  streaming:
    # You can uncomment the following lines if you want to not use the prebuilt image, for example if you have local code changes
    build:
      dockerfile: ./streaming/Dockerfile
      context: .
    image: kmyblue-streaming:15.0
```

`sidekiq`に関しては、コメントアウトか修正しておくのが望ましいとは思います。
修正するなら以下のようになります。
```yaml
  sidekiq:
    build: .
    image: kmyblue:15.0
```

全てにおいて、`image`をコメントアウトや修正せずUpstreamのままの記述でも問題なく動作はするようですが、中身の違うUpstreamと名前が同じ状態になってしまうので、何か不都合が出てきそうな気はします。
